'use client';

import { useGetGuideCards } from '@/core/api/generated/home/home';

/**
 * Example: using a generated React Query hook in a client component.
 *
 * Every hook is auto-generated by orval from core/openapi/api-docs.json.
 * Run `npm run api:generate` to regenerate after the OpenAPI spec changes.
 */
export function ReactQueryClientExample() {
  const { data, isPending, isError } = useGetGuideCards();

  if (isPending) return <p>Loading...</p>;
  if (isError) return <p>Failed to load.</p>;

  return (
    <ul>
      {(data?.data ?? []).map((card) => (
        <li key={card.id}>{card.id}</li>
      ))}
    </ul>
  );
}
