import { z } from 'zod';

/**
 * Login form validation schema.
 *
 * Note: API types (LoginRequest, AuthResponse) are auto-generated by Orval.
 * This schema is only for client-side form validation with React Hook Form.
 */
export const loginSchema = z.object({
  email: z.string().email('Please enter a valid email address'),
  password: z.string().min(8, 'Password must be at least 8 characters'),
});

export type LoginFormValues = z.infer<typeof loginSchema>;
